build site:
    image: node:12
    stage: build
    script:
        - npm install progress=false
        - npm run build
    artifacts:
        expire_in: 1 week
        paths:
            - dist

test:
    image: node:12
    stage: test
    script:
        - npm install progress=false
        - npm run test

deploy:
    image: node:12
    stage: deploy
    script:
        - ls
